### ISSUE TITLE
lua scripting:units: edit links need to be removed

### ISSUE THREAD

**Issue by andy5995** [glest/glest.io#17]
As I copied this info from the [MegaGlest wiki](https://docs.megaglest.org/MG/Lua), the *edit* links next to each function won't work on our web site and can be removed.

this is what the page looks like now

https://zetaglest.github.io/docs/lua_scripting_unit.html

And this is the file that must be edited.

https://github.com/ZetaGlest/zetaglest.github.io/blob/88161ea4f3f5692b6b62bd6a526044205fcdeebd/docs/infiles/lua_scripting_unit.sct#L4

**Comment by deviancyafoul** [comment]
Hello @andy5995 !

 I am a first-time contributor and I would like to help out.
 Is this issue still up for grabs?

Thanks!

**Comment by andy5995** [comment]
Yes it is!

**Comment by andy5995** [comment]
@infoalisaa I noticed your contribution wasn't recorded properly. If you'd like future contributions to appear on GitHub repo "contributors" sections, you should read https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/ (I think the problem is that your email isn't configured correctly in your local git configuration.)

You see in the commit log, your username appears but doesn't link back to your profile.
https://github.com/ZetaGlest/zetaglest.github.io/commits/master

Also, your username isn't appearing on the automated contributors page at https://github.com/ZetaGlest/zetaglest.github.io/graphs/contributors

Let me know if you have any questions.

**Comment by deviancyafoul** [comment]
Hi @andy5995 

 Well, after going through the help page you sent over and verifying that my email does match, I think the issue is because I forked the repository instead of pulling things into my own repository and then doing the pull request.
 It seems like the answer to this is the following:

Commit was made in a fork
Commits made in a fork will not count toward your contributions. To make them count, you must do one of the following:

Open a pull request to have your changes merged into the parent repository.
To detach the fork and turn it into a standalone repository on GitHub, contact GitHub Support. If the fork has forks of its own, let support know if the forks should move with your repository into a new network or remain in the current network. For more information, see "About forks."

 Before I submit another pull request, I was wondering if there was anything you could do on your end so I don't potentially mess something up.

 Can you let me know when you get the chance?

Thanks!

**Comment by andy5995** [comment]
Could you join our Discord chat room so we can troubleshoot this? https://discord.gg/WaAaXS7

Exchanging messages here adds to the amount of emails getting sent to repo watchers.
