### ISSUE TITLE
add instructions for creating game videos

### ISSUE THREAD

**Issue by andy5995** [glest/glest.io#56]
Can we get some instructions documented for creating game videos?

That could just be added to the top of the [videos page](https://zetaglest.github.io/docs/videos.html)

The repo file to edit is https://github.com/ZetaGlest/zetaglest.github.io/blob/master/docs/videos.html

**Comment by andy5995** [comment]
Probably better for the FAQ page, now that we have one.

https://zetaglest.github.io/docs/faq.html

**Comment by LinaJohnson** [comment]
@andy5995 I'd like to help out with this one.

**Comment by andy5995** [comment]
ok @LinaJohnson it's still open

**Comment by linux-player9** [comment]
It will be great that the page display correctly on a phone since a lot of people uses their phone to browse the web

**Comment by andy5995** [comment]
Looks like the stuff under docs/ displays right on mobile, but not the faction docs.

/cc @ZetaGlest/website

**Comment by escottalexander** [comment]
Responsive design is hard on a table. If we make the categories stack then it won't be clear which box goes with which label. Any ideas on how we can change it? One I have is to make it so that on mobile, all you see is a list of unit names until you click on one specific name, then it shows the info that goes with that unit. Thoughts? @ZetaGlest/website 

Also, this will need to be addressed when we build the JSON to HTML conversion function.

**Comment by andy5995** [comment]
Thanks for your feedback on that. I've opened a separate ticket for it https://github.com/ZetaGlest/zetaglest.github.io/issues/89

We'll keep this one on topic from now on. Sorry @LinaJohnson :blush:

**Comment by andy5995** [comment]
Oh, looks like she removed herself from the ticket. Ok this is still open.

**Comment by hodbadger** [comment]
I'd like to help, but this would be my first contribution and I don't know where to start - what should I read in order to document the instructions?
